### PR TITLE
underline function argument return types precisely

### LINKED ISSUE #181: imprecise underlining upon function argument returning invalid value
If the return value of a function *argument* is incorrect, the entire return type is underlined even if the outermost type is correct. For example:

```javascript
S.unfoldr (c => c <= 'z' ? S.Just (c) : S.Nothing) ('a');
// ! TypeError: Invalid value
//
//   unfoldr :: (b -> Maybe (Pair a b)) -> b -> Array a
//                    ^^^^^^^^^^^^^^^^
//                           1
//
//   1)  Just("a") :: Maybe String
//
//   The value at position 1 is not a member of ‘Maybe (Pair a b)’.
//
//   See https://github.com/sanctuary-js/sanctuary/tree/v0.14.1#MaybeType for information about the sanctuary/Maybe type.
```

Only `Pair a b` should be underlined in this case.

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #181

The updated code is simpler in addition to producing better error messages. :)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1147,49 +1140,27 @@
...
-                                   r.typeVarMap,
-                                   expType.types[k].type,
-                                   index,
-                                   Z.concat(propPath, [k]),
-                                   innerValues);
-                    },
-                    Z.reduce(function(e, x) {
-                      var t = expType.types[k].type;
-                      return Z.chain(function(r) {
-                        return test(env)(t)(x) ? Right(r) : Left(function() {
```
Comment (davidchambers) [inline index.js]: This was the problem. `test(env)(t)(x)` expands to `satisfactoryTypes(env, {name: 'name', constraints: {}, types: [t]}, {}, t, 0, [], [x]).isRight`, which throws away useful information in the failure case. This forced us to infer lost context below (see the uses of `typeVarConstraintViolation` and `invalidValue`).
